/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a;

import java.awt.CardLayout;

/**
 *
 * @author ACER
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_kurang = new javax.swing.JLabel();
        lb_tambah = new javax.swing.JLabel();
        lb_jumlah = new javax.swing.JLabel();
        bt_next = new javax.swing.JLabel();
        bt_back = new javax.swing.JLabel();
        lb_tambahpesan = new javax.swing.JLabel();
        lb_minuman = new javax.swing.JLabel();
        lb_makanan = new javax.swing.JLabel();
        panel_utama = new javax.swing.JPanel();
        makanan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        minuman = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lb_tambahmenu = new javax.swing.JLabel();
        lb_hapusmenu = new javax.swing.JLabel();
        lb_editmenu = new javax.swing.JLabel();
        lb_exit = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lb_kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 280, 20, 15));
        getContentPane().add(lb_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 20, 15));
        getContentPane().add(lb_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 272, 60, 28));

        bt_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_nextMouseClicked(evt);
            }
        });
        getContentPane().add(bt_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 492, 72, 30));

        bt_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_backMouseClicked(evt);
            }
        });
        getContentPane().add(bt_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 72, 30));

        lb_tambahpesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_tambahpesanMouseClicked(evt);
            }
        });
        getContentPane().add(lb_tambahpesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 402, 220, 30));

        lb_minuman.setToolTipText("");
        lb_minuman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_minumanMouseClicked(evt);
            }
        });
        getContentPane().add(lb_minuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 15, 220, 50));

        lb_makanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_makananMouseClicked(evt);
            }
        });
        getContentPane().add(lb_makanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 190, 50));

        panel_utama.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "makanan", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout makananLayout = new javax.swing.GroupLayout(makanan);
        makanan.setLayout(makananLayout);
        makananLayout.setHorizontalGroup(
            makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makananLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        makananLayout.setVerticalGroup(
            makananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        panel_utama.add(makanan, "card_makanan");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "minuman", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout minumanLayout = new javax.swing.GroupLayout(minuman);
        minuman.setLayout(minumanLayout);
        minumanLayout.setHorizontalGroup(
            minumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        minumanLayout.setVerticalGroup(
            minumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        panel_utama.add(minuman, "card_minuman");

        getContentPane().add(panel_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 545, 455));
        getContentPane().add(lb_tambahmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 140, 30));
        getContentPane().add(lb_hapusmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 165, 140, 30));
        getContentPane().add(lb_editmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 140, 30));
        getContentPane().add(lb_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 5, 20, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/menu rev.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_makananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_makananMouseClicked
        //membuka tabel makanan
        CardLayout clayout = (CardLayout) panel_utama.getLayout();
        clayout.show(panel_utama, "card_makanan");
    }//GEN-LAST:event_lb_makananMouseClicked

    private void lb_minumanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minumanMouseClicked
        //membuka tabel minuman
        CardLayout clayout = (CardLayout) panel_utama.getLayout();
        clayout.show(panel_utama, "card_minuman");
    }//GEN-LAST:event_lb_minumanMouseClicked

    private void bt_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_nextMouseClicked
        //pindah ke form sebelumnya
        Index i = new Index();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_nextMouseClicked

    private void bt_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_backMouseClicked
        //pindah ke form selanjutnya
    }//GEN-LAST:event_bt_backMouseClicked

    private void lb_tambahpesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tambahpesanMouseClicked
        //pindah ke form 
        //beri peringatan (?) kalau pesanan sudah berhasil ditambahkan lalu bari kluk tombol next buat ke form selanjutnya
        
    }//GEN-LAST:event_lb_tambahpesanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bt_back;
    private javax.swing.JLabel bt_next;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lb_editmenu;
    private javax.swing.JLabel lb_exit;
    private javax.swing.JLabel lb_hapusmenu;
    private javax.swing.JLabel lb_jumlah;
    private javax.swing.JLabel lb_kurang;
    private javax.swing.JLabel lb_makanan;
    private javax.swing.JLabel lb_minuman;
    private javax.swing.JLabel lb_tambah;
    private javax.swing.JLabel lb_tambahmenu;
    private javax.swing.JLabel lb_tambahpesan;
    private javax.swing.JPanel makanan;
    private javax.swing.JPanel minuman;
    private javax.swing.JPanel panel_utama;
    // End of variables declaration//GEN-END:variables
}
